### ISSUE TITLE
Install from PyPi fails

### ISSUE THREAD

**Issue by jayvdb** [yeger00/pylspclient#50]
Downloading the source uploaded to PyPI and attempting to build a wheel fails.  Presumably the same error would occur when attempting to install it.

```
[   13s] + /usr/bin/python3.9 -mpip wheel --verbose --progress-bar off --disable-pip-version-check --use-pep517 --no-build-isolation --no-deps --wheel-dir ./build .
[   13s] Processing /home/abuild/rpmbuild/BUILD/pylspclient-0.1.0
[   13s]   Preparing metadata (pyproject.toml): started
[   13s]   Running command Preparing metadata (pyproject.toml)
[   14s]   Traceback (most recent call last):
[   14s]     File "/usr/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
[   14s]       main()
[   14s]     File "/usr/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
[   14s]       json_out['return_val'] = hook(**hook_input['kwargs'])
[   14s]     File "/usr/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
[   14s]       return hook(metadata_directory, config_settings)
[   14s]     File "/usr/lib/python3.9/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
[   14s]       builder = WheelBuilder(poetry)
[   14s]     File "/usr/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 62, in __init__
[   14s]       super().__init__(poetry, executable=executable)
[   14s]     File "/usr/lib/python3.9/site-packages/poetry/core/masonry/builders/builder.py", line 50, in __init__
[   14s]       self._meta = Metadata.from_package(self._package)
[   14s]     File "/usr/lib/python3.9/site-packages/poetry/core/masonry/metadata.py", line 58, in from_package
[   14s]       with readme.open(encoding="utf-8") as f:
[   14s]     File "/usr/lib64/python3.9/pathlib.py", line 1252, in open
[   14s]       return io.open(self, mode, buffering, encoding, errors, newline,
[   14s]     File "/usr/lib64/python3.9/pathlib.py", line 1120, in _opener
[   14s]       return self._accessor.open(self, flags, mode)
[   14s]   FileNotFoundError: [Errno 2] No such file or directory: '/home/abuild/rpmbuild/BUILD/pylspclient-0.1.0/README.md'
```

**Comment by yeger00** [comment]
HI @jayvdb , thanks for opening the issue.
I think that the problem is due to the pyproject.toml direct to `README.md` which is a softlink to `docs/README.md`. I will fix it later on today.
Out of curiosity, what are you trying to achieve by building it from the pypi source, rather than the Github repo or the already built pypi package?

Thanks,
Avi

**Comment by jayvdb** [comment]
Thanks.  I create packages for all packages I am interested in installing.  If I cant get them building as a distro package, I look for another solution that will be more maintainable .
https://build.opensuse.org/package/show/home:jayvdb:py-new/python-pylspclient

**Comment by yeger00** [comment]
Tested it locally and it seems to fix the issue. Let me know if that works for you:
```
(venv) pylspclient-0.1.1 % pip wheel --verbose --progress-bar off --disable-pip-version-check --use-pep517 --no-build-isolation --no-deps --wheel-dir ./build .
Processing ./pylspclient-0.1.1
  Running command Preparing metadata (pyproject.toml)
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pylspclient
  Running command Building wheel for pylspclient (pyproject.toml)
  Building wheel for pylspclient (pyproject.toml) ... done
  Created wheel for pylspclient: filename=pylspclient-0.1.1-py3-none-any.whl size=10638 sha256=891d0baedf18cedda84c8b95f24bb989d51528966702592448f6f1f692730a64
  Stored in directory: /Users/yeger/Library/Caches/pip/wheels/33/c5/37/2ddda248e8e7d94ca5a2d04a154fd24ad70df1c9ff803eaf74
Successfully built pylspclient
```

**Comment by jayvdb** [comment]
Thanks. My build is green now.
